version: '3.8'

services:
  app:
    container_name: s3-golang-dev
    image: s3-golang-dev:latest
    ports:
      - '5000:5000'
    restart: on-failure
    environment:
      DB_URL: 'postgres://s3-golang:@db:5432/s3-golang?sslmode=disable'
    networks:
      - s3-golang
  db:
    container_name: s3-golang-db
    image: postgres:latest
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - 'db:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: s3-golang
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - s3-golang
  db-migrate:
    container_name: s3-golang-db-migrate
    image: migrate/migrate:latest
    restart: 'no'
    command:
      [
        '-path',
        '/migrations',
        '-database',
        'postgres://s3-golang:@db:5432/s3-golang?sslmode=disable',
        'up',
      ]
    depends_on:
      - db
    volumes:
      - ./data/migrations:/migrations
    networks:
      - s3-golang

volumes:
  db:
networks:
  s3-golang:
