version: '3.8'

services:
  app:
    container_name: s3-golang-assignment-app
    image: s3-golang-assignment-app:latest
    ports:
      - '5000:5000'
    restart: on-failure
    environment:
      DB_URL: 'postgres://s3-golang-assigment:@db:5432/s3-golang-assignment?sslmode=disable'
      APP_PORT: 5000
    networks:
      - s3-golang-assignment
  db:
    container_name: s3-golang-assigment-db
    image: postgres:latest
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - 'db:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: s3-golang-assigment
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - s3-golang-assignment
  db-migrate:
    container_name: s3-golang-assignment-db-migrate
    image: migrate/migrate:latest
    depends_on:
      - db
    volumes:
      - ./data/migrations:/migrations
    networks:
      - s3-golang-assignment

volumes:
  db:
networks:
  s3-golang-assignment:
